name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        include:
          - os: ubuntu-20.04
            ruby: '2.7'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@ff740bc00a01b3a50fffc55a1071b1060eeae9dc # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          bundle exec appraisal install --path=vendor/bundle
      - name: Run tests
        run: bundle exec appraisal rake test
