name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@d5fb7a202fc07872cb44f00ba8e6197b70cb0c55 # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          bundle exec appraisal install --path=vendor/bundle
      - name: Run tests
        run: bundle exec appraisal rake test
